config/routes.rb
Rails.application.routes.draw do
  resources :interviews
  resources :opp_parties
  resources :documents
  resources :profiles, only: [:edit, :show, :update]
  get 'welcome/index'

  get 'welcome/features'

  get 'welcome/contact'

  get 'welcome/about'

  devise_for :users

  root to: 'welcome#index'

end

app/models/opp_party.rb
class OppParty < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  has_many :documents
end

app/controllers/opp_parties_controller.rb
class OppPartiesController < ApplicationController
  before_action :set_opp_party, only: [:show, :edit, :update, :destroy]

  # GET /opp_parties
  # GET /opp_parties.json
  def index
    @opp_parties = OppParty.where(:user_id => current_user.id)
  end

  # GET /opp_parties/1
  # GET /opp_parties/1.json
  def show
    @opp_party = OppParty.find(params[:id])
  end

  # GET /opp_parties/new
  def new
    @opp_party = OppParty.new
  end

  # GET /opp_parties/1/edit
  def edit
  end

  # POST /opp_parties
  # POST /opp_parties.json
  def create
    @opp_party = OppParty.new(opp_party_params)
    @opp_party.user_id = current_user.id 

    respond_to do |format|
      if @opp_party.save
        format.html { redirect_to @opp_party, notice: 'Opp party was successfully created.' }
        format.json { render :show, status: :created, location: @opp_party }
      else
        format.html { render :new }
        format.json { render json: @opp_party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /opp_parties/1
  # PATCH/PUT /opp_parties/1.json
  def update
    respond_to do |format|
      if @opp_party.update(opp_party_params)
        format.html { redirect_to @opp_party, notice: 'Opp party was successfully updated.' }
        format.json { render :show, status: :ok, location: @opp_party }
      else
        format.html { render :edit }
        format.json { render json: @opp_party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /opp_parties/1
  # DELETE /opp_parties/1.json
  def destroy
    @opp_party.destroy
    respond_to do |format|
      format.html { redirect_to opp_parties_url, notice: 'Opp party was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_opp_party
      @opp_party = OppParty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def opp_party_params
      params.require(:opp_party).permit(:user_id, :first_name, :last_name, :birth_date, :ssn, :home_phone, :work_phone, :cell_phone, :case_number, :add_line1, :add_line2, :add_city, :add_state, :add_zip, :gender, :height, :weight, :dl_number, :dl_state)
    end
end

app/helpers/opp_parties_helper.rb
module OppPartiesHelper
end

app/views/opp_parties/_form.html.erb
<%= form_for(@opp_party) do |f| %>
  <% if @opp_party.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@opp_party.errors.count, "error") %> prohibited this opp_party from being saved:</h2>

      <ul>
      <% @opp_party.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %> <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %> <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :birth_date %>
    <%= f.date_field :birth_date %>
  </div>
  <div class="field">
    <%= f.label :ssn %>
    <%= f.text_field :ssn %>
  </div>
  <div class="field">
    <%= f.label :home_phone %>
    <%= f.text_field :home_phone %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/opp_parties/edit.html.erb
<h1>Editing Opp Party</h1>

<%= render 'form' %>

<%= link_to 'Show', @opp_party %> |
<%= link_to 'Back', opp_parties_path %>

app/views/opp_parties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Opp Parties</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @opp_parties.each do |opp_party| %>
      <tr>
        <td><%= opp_party.first_name %></td>
        <td><%= opp_party.last_name %></td>
        <td><%= opp_party.birth_date %></td>
        <td><%= opp_party.ssn %></td>
        <td><%= opp_party.home_phone %></td>
        <td><%= link_to 'Show', opp_party %></td>
        <td><%= link_to 'Edit', edit_opp_party_path(opp_party) %></td>
        <td><%= link_to 'Destroy', opp_party, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Opp party', new_opp_party_path %>

app/views/opp_parties/new.html.erb
<h1>New Opp Party</h1>

<%= render 'form' %>

<%= link_to 'Back', opp_parties_path %>

app/views/opp_parties/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>User ID:</strong>
  <%= @opp_party.user_id %>
</p>
<p>
<p>
  <strong>Name:</strong>
  <%= @opp_party.first_name + " " + @opp_party.last_name %>
</p>
<p>
  <strong>Birth date:</strong>
  <%= @opp_party.birth_date %>
</p>
<p>
  <strong>Ssn:</strong>
  <%= @opp_party.ssn %>
</p>
<p>
  <strong>Home phone:</strong>
  <%= @opp_party.home_phone %>
</p>


<%= link_to 'Edit', edit_opp_party_path(@opp_party) %> |
<%= link_to 'Back', opp_parties_path %>