config/routes.rb
Rails.application.routes.draw do
  resources :interviews
  resources :opp_parties
  resources :documents
  resources :profiles, only: [:edit, :show, :update]
  get 'welcome/index'

  get 'welcome/features'

  get 'welcome/contact'

  get 'welcome/about'

  devise_for :users

  root to: 'welcome#index'

end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_action :set_interview, only: [:show, :edit, :update, :destroy]

  # GET /interviews
  # GET /interviews.json
  def index
    @interviews = Interview.all
  end

  # GET /interviews/1
  # GET /interviews/1.json
  def show
    @interview = Interview.find(params[:id])
  end

  # GET /interviews/new
  def new
    @interview = Interview.new
  end

  # GET /interviews/1/edit
  def edit
  end

  # POST /interviews
  # POST /interviews.json
  def create
    @interview = Interview.new(params [:interview])
#     @interview.document_id = @interview.document.find(params [:id])

    respond_to do |format|
      if @interview.save
        format.html { redirect_to @interview, notice: 'Interview was successfully created.' }
        format.json { render :show, status: :created, location: @interview }
      else
        format.html { render :new }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interviews/1
  # PATCH/PUT /interviews/1.json
  def update
    respond_to do |format|
      if @interview.update(interview_params)
        format.html { redirect_to @interview, notice: 'Interview was successfully updated.' }
        format.json { render :show, status: :ok, location: @interview }
      else
        format.html { render :edit }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interviews/1
  # DELETE /interviews/1.json
  def destroy
    @interview.destroy
    respond_to do |format|
      format.html { redirect_to interviews_url, notice: 'Interview was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interview
      @interview = Interview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interview_params
      params.require(:interview).permit(:yn01, :yn02, :yn03, :yn04, :yn05, :yn06, :document)
    end
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/views/interviews/_form.html.erb
<%= form_for(@interview) do |f| %>
  <% if @interview.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interview.errors.count, "error") %> prohibited this interview from being saved:</h2>

      <ul>
      <% @interview.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :yn01 %><br>
    <%= f.text_field :yn01 %>
  </div>
  <div class="field">
    <%= f.label :yn02 %><br>
    <%= f.text_field :yn02 %>
  </div>
  <div class="field">
    <%= f.label :yn03 %><br>
    <%= f.text_field :yn03 %>
  </div>
  <div class="field">
    <%= f.label :yn04 %><br>
    <%= f.text_field :yn04 %>
  </div>
  <div class="field">
    <%= f.label :yn05 %><br>
    <%= f.text_field :yn05 %>
  </div>
  <div class="field">
    <%= f.label :yn06 %><br>
    <%= f.text_field :yn06 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interviews/edit.html.erb
<h1>Editing Interview</h1>

<%= render 'form' %>

<%= link_to 'Show', @interview %> |
<%= link_to 'Back', interviews_path %>

app/views/interviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Interviews</h1>

<table>
  <thead>
    <tr>
      <th>Yn01</th>
      <th>Yn02</th>
      <th>Yn03</th>
      <th>Yn04</th>
      <th>Yn05</th>
      <th>Yn06</th>
      <th>Document</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interviews.each do |interview| %>
      <tr>
        <td><%= interview.yn01 %></td>
        <td><%= interview.yn02 %></td>
        <td><%= interview.yn03 %></td>
        <td><%= interview.yn04 %></td>
        <td><%= interview.yn05 %></td>
        <td><%= interview.yn06 %></td>
        <td><%= interview.document %></td>
        <td><%= link_to 'Show', interview %></td>
        <td><%= link_to 'Edit', edit_interview_path(interview) %></td>
        <td><%= link_to 'Destroy', interview, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Interview', new_interview_path %>

app/views/interviews/new.html.erb
<h1>New Interview</h1>

<%= render 'form' %>

<%= link_to 'Back', interviews_path %>

app/views/interviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Yn01:</strong>
  <%= @interview.yn01 %>
</p>

<p>
  <strong>Yn02:</strong>
  <%= @interview.yn02 %>
</p>

<p>
  <strong>Yn03:</strong>
  <%= @interview.yn03 %>
</p>

<p>
  <strong>Yn04:</strong>
  <%= @interview.yn04 %>
</p>

<p>
  <strong>Yn05:</strong>
  <%= @interview.yn05 %>
</p>

<p>
  <strong>Yn06:</strong>
  <%= @interview.yn06 %>
</p>

<p>
  <strong>Document:</strong>
  <%= @interview.document %>
</p>

<%= link_to 'Edit', edit_interview_path(@interview) %> |
<%= link_to 'Back', interviews_path %>