config/routes.rb
Rails.application.routes.draw do
  resources :interviews
  resources :opp_parties
  resources :documents
  resources :profiles, only: [:edit, :show, :update]
  get 'welcome/index'

  get 'welcome/features'

  get 'welcome/contact'

  get 'welcome/about'

  devise_for :users

  root to: 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lamalaw2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <ul class="nav nav-pills lamalaw2">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Features", welcome_features_path %></li>
    <li><%= link_to "Contact", welcome_contact_path %></li>
    <li><%= link_to "About Us", welcome_about_path %></li>
    <% if current_user %>

    <% else %>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <li><%= link_to "Sign In", new_user_session_path %></li>
    <% end %>
    <% if user_signed_in? %>
       <div class="nav pull-right">
         <ul class="nav nav-pills">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.email %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Documents", documents_path %></li>
              <li><%= link_to "Profile", profile_path(current_user) %></li> 
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              <li class="divider"></li>
            </ul>
          </li>
         </ul>
      </div>
    <% end %>
  </ul>



  <%= yield %>
</div>

</body>
</html>